server {
    listen 443 ssl http2;
    server_name beef.l777.casino;
    root /var/www/beef.l777.casino;
    index index.html;

    ssl_certificate     /etc/ssl/beef.l777.casino/fullchain.pem;
    ssl_certificate_key /etc/ssl/beef.l777.casino/privkey.pem;

    location / {
        try_files $uri $uri/ /index.html =404;
    }
}
